markdown: kramdown
highlighter: rouge
paginate: 100
language: 'en-us'
baseurl: /
title: Jorijn Schrijvershof
description: A 28-year old Freelance Web Developer from Brabant, The Netherlands
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
production_url: https://jorijn.com/
source_url: https://github.com/jorijn/jorijn.com/
navigation: True
subscribers: False
twitter: jorijn
facebook: jorijnschrijvershof
disqus: False
disqus_shortname: False
google_analytics: False
permalink: /:title/
plugins: [jekyll-paginate, jekyll-feed, octopress-minify-html]
feed:
  path: feed.xml
kramdown:
  input: GFM
  syntax_highlighter: rouge