title: Jorijn Schrijvershof
author: Jorijn Schrijvershof
email: jorijn@jorijn.com
url: https://jorijn.com
description: A 29-year old Freelance Web Developer from Brabant, The Netherlands
show_excerpts: false
permalink: /:title/

moving:
  avatar_url: "https://avatars1.githubusercontent.com/u/85466" # avatar in about page
  about_you: A 29-year old Freelance Web Developer from Brabant, The Netherlands
  date_format: "%b %d"
  back_to: "Home"

  social_links:
    twitter: jorijn
    github: jorijn
    rss: RSS
    facebook: jschrijvershof
    linkedin: jorijnschrijvershof
    telegram: jorijn
